### ISSUE TITLE
Slider: `outside a reactive tracking context` on mount, `called Result::unwrap() on an Err value: OwnerDisposed(Owner(NodeId(1223v3)))`

### ISSUE THREAD

**Issue by zakstucke** [leptix/leptix#27]
As mentioned in #26. 

These errors don't seem to crash the slider/app usage, but obviously I'm sure will still cause problems. 

On mount 100s of these:
```
At /Users/zak/z/code/leptix/crates/primitives/src/components/slider.rs:738:25, you access a signal or memo (defined at /Users/zak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.6.11/src/node_ref.rs:70:13) outside a reactive tracking context. This might mean your app is not responding to changes in signal values in the way you expect.

Here’s how to fix it:

1. If this is inside a `view!` macro, make sure you are passing a function, not a value.
  ❌ NO  <p>{x.get() * 2}</p>
  ✅ YES <p>{move || x.get() * 2}</p>

2. If it’s in the body of a component, try wrapping this access in a closure: 
  ❌ NO  let y = x.get() * 2
  ✅ YES let y = move || x.get() * 2.

3. If you’re *trying* to access the value without tracking, use `.get_untracked()` or `.with_untracked()` instead.
```

On unmount a bunch of these:
```
Panic: called `Result::unwrap()` on an `Err` value: OwnerDisposed(Owner(NodeId(1223v3)))
    at app.wasm.__rust_start_panic (app.wasm:0x241ee8c)
    at app.wasm.rust_panic (app.wasm:0x241c9ee)
    at app.wasm.std::panicking::rust_panic_with_hook::h32c80a64fe4de396 (app.wasm:0x2007366)
    at app.wasm.std::panicking::begin_panic_handler::{{closure}}::hd496964d114e98b9 (app.wasm:0x214297b)
    at app.wasm.std::sys_common::backtrace::__rust_end_short_backtrace::h0d4686a7fe3981a4 (app.wasm:0x241dd65)
    at app.wasm.rust_begin_unwind (app.wasm:0x23841aa)
    at app.wasm.core::panicking::panic_fmt::hc7427f902a13f1a9 (app.wasm:0x23a92e9)
    at app.wasm.core::result::unwrap_failed::h8c7a47192e7f0267 (app.wasm:0x220cf21)
    at app.wasm.leptos_reactive::runtime::with_owner::h62b4fe86ac301565 (app.wasm:0x1ee6867)
    at app.wasm.leptos_reactive::effect::create_effect::{{closure}}::h3dbda75a1fdd6054 (app.wasm:0x2122721)
```

**Comment by Upbolt** [comment]
yeah looks like there are a few places i need to swap out .get() for .get_untracked()

its also kind of funny how a bit misleading the warning's line info is, it seems to mark the place where signal value being tracked is created instead of the actual location where the value is being read, means i'll have to manually go through and see where i need to replace it with .get_untracked()

**Comment by Upbolt** [comment]
wow this one was an annoying one to track down, but i finally squashed the last untracked signal https://github.com/leptix/leptix/blob/655a4d3905f17f335fc67365187aa0dfce0ebec5/crates/primitives/src/components/slider.rs#L842-L844

**Comment by zakstucke** [comment]
@Upbolt just tried your branch seems much better! Although on onmount still get these 3:

```
[Signal::update] At Location { file: "/Users/zak/.cargo/git/checkouts/leptix-0681cd48f7724afe/83c468a/crates/primitives/src/components/collection.rs", line: 63, col: 16 }, you’re trying to update a Signal<std::collections::hash::map::HashMap<leptix_primitives::components::collection::CollectionItemId, (leptos_dom::node_ref::NodeRef<leptos_dom::html::AnyElement>, leptix_primitives::components::slider::SliderCollectionItem)>> (defined at /Users/zak/.cargo/git/checkouts/leptix-0681cd48f7724afe/83c468a/crates/primitives/src/components/slider.rs:195:15) that has already been disposed of. This is probably a logic error in a component that creates and disposes of scopes. If it does not cause any issues, it is safe to ignore this warning, which occurs only in debug mode.

Attempted to update a signal after it was disposed.
signal created here: /Users/zak/.cargo/git/checkouts/leptix-0681cd48f7724afe/83c468a/crates/primitives/src/components/slider.rs:195:15
warning happened here: /Users/zak/.cargo/git/checkouts/leptix-0681cd48f7724afe/83c468a/crates/primitives/src/components/collection.rs:63:16

ERROR: 
      /Users/zak/.cargo/git/checkouts/leptix-0681cd48f7724afe/83c468a/crates/primitives/src/components/slider.rs:807:22
      Panic: could not set stored value
```

**Comment by Upbolt** [comment]
think you can send a quick repro?

**Comment by zakstucke** [comment]
Will try to in a few hours 👍

**Comment by Upbolt** [comment]
actually i think i got it, but while testing unmounts i was getting some panics with:
- ScrollArea
- ToggleGroup
- RadioGroup
- Toolbar (by proxy of RadioGroup)

**Comment by zakstucke** [comment]
It's *soo* close now, down to 2 errors for me now, both on unmount.

`1.`
Specifically, I pass a `derive` signal to `SliderRoot`'s `values` prop, on unmount this signal panics as it's called after the signals inside it have already been disposed of.

Most likely meaning the leptix slider is trying to `.get` the `values` prop after unmount for some reason, which triggers the panic. 

`2.`
```
ERROR: 
      /Users/zak/.cargo/git/checkouts/leptix-0681cd48f7724afe/3ca0163/crates/primitives/src/components/collection.rs:88:48
      Panic: Attempted to get a signal after it was disposed.
      signal created here: /Users/zak/.cargo/registry/src/index.crates.io-6f17d22bba15001f/leptos_dom-0.6.11/src/node_ref.rs:70:13
      warning happened here: /Users/zak/.cargo/git/checkouts/leptix-0681cd48f7724afe/3ca0163/crates/primitives/src/components/collection.rs:88:48
```

Does that ring enough bells or shall I try the repro?

**Comment by zakstucke** [comment]
Also fyi on an entirely separate bug, not important at all for me but I noticed it whilst trying things out:

Setting `min_steps_between_thumbs` seems to break multi thumb sliders, when it's set the thumbs get stuck on top of each other.

`min_steps_between_thumbs` not set works fine:

https://github.com/leptix/leptix/assets/44890343/c984c9be-1267-436d-ad60-1488fc3426dc

`min_steps_between_thumbs=1.0.into()` + `step=1.0`

https://github.com/leptix/leptix/assets/44890343/4845247e-ac0e-4f3a-95e1-b6791b89e1ef

**Comment by Upbolt** [comment]
aw, yeah i guess you can send in a repro now then

**Comment by Upbolt** [comment]
feel free to make a separate issue for min_steps, i'll take a look at it after we get this resolved

**Comment by zakstucke** [comment]
I've managed to reproduce both!

1. Leptix issue:
- To see on it's own, shift the `value` signal from inside the `<Show/>` to outside to nullify `2.`.

2. `value` signal accessed after unmount.
- To see on it's own, remove the `input_ref`/`node_ref` to nullify `1.`

As is produces `1.` on first toggle click, `2.` on second:

https://github.com/leptix/leptix/assets/44890343/c8bc4a41-8dc8-4ee8-9503-5d0f1961d160

```rust
use leptos::*;

use leptix_primitives::components::slider::{SliderRange, SliderRoot, SliderThumb, SliderTrack};

#[component]
pub fn UiScratchSpace() -> impl IntoView {
    let show = RwSignal::new(true);
    let zoom = RwSignal::new(1);
    view! {
        <button on:click=move |_| show.set(!show.get())>"Toggle Show"</button>
        <Show when=move || show.get()>
            <MySlider
                value=Signal::derive(move || zoom.get() as f64)
                on_change=Callback::new(move |val: f64| {
                    zoom.try_set(val as usize);
                })
            />

        </Show>
    }
}

#[component]
fn MySlider(value: Signal<f64>, on_change: Callback<f64>) -> impl IntoView {
    let input_ref = create_node_ref::<html::AnyElement>();
    view! {
        <div style="width: 100%; padding: 30px;">
            {move || {
                view! {
                    <SliderRoot
                        node_ref=input_ref
                        step=1.0.into()
                        value=Signal::derive(move || { vec![value.get()] }).into()
                        min=1.0.into()
                        max=100.0.into()
                        attr:style="height: 1rem; width: 100%; display: flex; align-items: center; position: relative;"
                        on_value_change=Callback::new(move |vals: Vec<f64>| {
                            on_change.call(*vals.first().unwrap());
                        })
                    >

                        <SliderTrack attr:style="background-color: gray; height: 3px; width: 100%;">
                            <SliderRange attr:style="background-color: gray; position: absolute; height: 100%;">
                                {().into_view()}
                            </SliderRange>
                        </SliderTrack>

                        <SliderThumb attr:style="display: block; width: 1rem; height: 1rem; background-color: red;">
                            <div></div>
                        </SliderThumb>

                    </SliderRoot>
                }
            }}

        </div>
    }
}

```

**Comment by Upbolt** [comment]
thanks a bunch, i'll look into it!

**Comment by zakstucke** [comment]
no prob, the snipper probably could still be made simpler, the layers of signals and the random `move || view!{}` in slider were traces of the source code, might not be required for the bugs.

**Comment by zakstucke** [comment]
@Upbolt I tried out your PR and seems to solve everything kudos! 

Are there any blockers to merging in and cutting a release?

**Comment by Upbolt** [comment]
there are still some issues when unmounting multiple components that use the internal [collection](https://github.com/leptix/leptix/blob/f2fb3630aa7279986de803ae5bafee0c3ce92967/crates/primitives/src/components/collection.rs) context that i'm figuring out right now, but i'm glad the changes were at least able to fix your issues 🤣

i just wanna get a few more bug fixes in before i drop a little minor release

**Comment by Upbolt** [comment]
so this issue has become pretty interesting, i'm chipping away at it slowly and have discovered this behavior

slider before other components using collection context
![](https://i.gyazo.com/8f4bb53e292dd21b5c3befa47c9b5e54.gif)

slider after other components using collection context
![](https://i.gyazo.com/12cff594625e2c92afde77e59e542649.gif)

**Comment by zakstucke** [comment]
Weird, the slider's the only component i'm using right now, I don't think I've encountered this yet

**Comment by Upbolt** [comment]
holyyyyyy wow, it took me SOOO damn long to find out the source of this issue because the error messages kept pointing to slider, when the issue wasn't in slider at all. it was in roving_focus and radio_group; apparently leptos-use's use_event_listener is causing issues which i'll investigate in a separate issue, but for now commenting them out solves this complete headache of an issue

https://github.com/leptix/leptix/blob/714cabce726646e9e68dce4ba525fbfb3fb67fd9/crates/primitives/src/components/radio_group.rs#L144-L152

https://github.com/leptix/leptix/blob/714cabce726646e9e68dce4ba525fbfb3fb67fd9/crates/primitives/src/components/roving_focus.rs#L119-L123

**Comment by zakstucke** [comment]
Sorry it ended up being such a nightmare, awesome you worked it all out though! 
I've just updated to latest commit and can't see anything wrong :)
