### ISSUE TITLE
How to use tabs with tailwind+daisy

### ISSUE THREAD

**Issue by marcbowes** [leptix/leptix#41]
Hi! I just started looking at this library. I really like that it's style agnostic!

I was looking at the tab demo and I see that you set `data-state=active` and apply css classes conditionally on that state. I get how that works. But, I was hoping to do something much simpler with something like https://daisyui.com/components/tab/#lifted where I can just set `tab-active` as a conditional class.

I think I know how to do this. I can capture the tab value in a signal then conditionally set each `TabsTrigger` class. I was wondering if there is a cleaner way to do this, given that internally the component already knows if it's active.

**Comment by marcbowes** [comment]
The simplest solution I found was to

1. add `attr:class="tab"` to each `<TabsTrigger .. />
2. Add to tailwind.css:

```@layer base {
    [role="tab"][data-state="active"] {
        @apply tab-active;
    }
}
```

Note: I tried to also apply the tab class instead of repeating it per trigger, but that doesn't work (since tailwind uses the `.tab` selector).

**Comment by Upbolt** [comment]
i'm not completely sure either as i don't use any css libraries besides tailwind, but according to https://tailwindcss.com/docs/hover-focus-and-other-states#using-with-your-own-classes

modifiers are available on tailwind layers and classes added through plugins, which daisy-ui seems to do https://daisyui.com/docs/install/

so theoretically you should just be able to do the following?
```jsx
<TabsList
  attr:class="tabs"
  attr:aria-label="Manage your account"
>
  <TabsTrigger attr:class="tab data-[state=active]:tab-active" value="tab1">
    "Account"
  </TabsTrigger>
  <TabsTrigger attr:class="tab data-[state=active]:tab-active" value="tab2">
    "Password"
  </TabsTrigger>
</TabsList>
```

**Comment by marcbowes** [comment]
That worked, thank you!
